/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RSA;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.Formatter;
import java.util.Random;
import java.util.Scanner;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.KeyGenerator;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Ben
 */
public class frmRSA extends javax.swing.JFrame {

    /**
     * Creates new form frmRSA
     */
    public frmRSA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void readFile(){
         JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();
        String out = "";
        if(f != null){
            try {
                Scanner sc = new Scanner(f);
                
                while(sc.hasNext()){
                    out += sc.nextLine();
                }
                txtPlainText.setText(out);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane,"cannot open file");          
            }
        }
    }
    private void writeFile(){
    
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showSaveDialog(this);
        //file select
        File f = chooser.getSelectedFile();
        
        if(f != null){
            Formatter saveFile;
            try {
                String input = txtCipherText.getText();
                saveFile = new Formatter(f);
                saveFile.format("%s", input);
                saveFile.close();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane,"cannot open file");

            }
        
    }
    }
    // <editor-fold defaultstate="collapsed" desc="Global variable"> 
       int p = randomNumber();
       int q = randomNumber();
       int e = gcd(p, q);
       int N = getN(p, q);
       int n = getPhiN(p, q);
       int d = calculateD(e, n);
       int[] Kpublic = new int[]{e,N};
       int[] Kprivate = new int[]{d,N};

    // </editor-fold> 
    
     // <editor-fold defaultstate="collapsed" desc="Function"> 
    private int randomNumber() {
        Random rand = new Random();
        int limit = 10;
        int value = rand.nextInt(limit) + 1;
        return value;
    }

    private int getN(int p, int q) {
        return p * q;
    }

    private int getPhiN(int p, int q) {
        return (p - 1) * (q - 1);
    }

    private int gcd(int e, int N) { //UCLN
        int r;
        while (N != 0) {
            r = e % N;
            e = N;
            N = r;
        }
        return e;
    }
    private int calculateD(int e, int n) {
        int i = 0;
        while (true) {
            if ((i * n + 1) % e == 0) {
                return (i * n + 1) / e;
            }
            i++;
        }
    }
// </editor-fold> 
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPlainText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCipherText = new javax.swing.JTextField();
        cboCipherStyle = new javax.swing.JComboBox<>();
        btnEncrypt = new javax.swing.JButton();
        btnDecrypt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPlainText1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPlainText2 = new javax.swing.JTextField();
        btnChoose = new javax.swing.JButton();
        lblFileChoose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("PlainText");

        jLabel2.setText("CipherText");

        cboCipherStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hóa bảo mật", "mã hóa chiến thuật" }));
        cboCipherStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCipherStyleActionPerformed(evt);
            }
        });

        btnEncrypt.setText("Encrypt");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnDecrypt.setText("Decrypt");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RSA ");

        jLabel4.setText("Private Key");

        jLabel5.setText("Public Key");

        btnChoose.setText("Choose File");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnChoose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFileChoose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboCipherStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(btnEncrypt)
                        .addGap(18, 18, 18)
                        .addComponent(btnDecrypt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtPlainText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCipherText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtPlainText1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlainText2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPlainText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPlainText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCipherStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncrypt)
                    .addComponent(btnDecrypt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCipherText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnChoose)
                    .addComponent(lblFileChoose))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCipherStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCipherStyleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCipherStyleActionPerformed

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
                try{   
        readFile();
        JOptionPane.showMessageDialog(null, "Mở thành công");
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, "Mở thất bại");
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         try{   
        writeFile();
       
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, "Lưu thất bại");
        }
    }//GEN-LAST:event_btnSaveActionPerformed
                                             
//     private void readFile(){
//         JFileChooser chooser = new JFileChooser();
//        chooser.showOpenDialog(this);
//        File f = chooser.getSelectedFile();
//        String out = "";
//        if(f != null){
//            try {
//                Scanner sc = new Scanner(f);
//                
//                while(sc.hasNext()){
//                    out += sc.nextLine();
//                }
//                txtPlainText.setText(out);
//                 txtPlainText.setEditable(false);
//              
//            } catch (FileNotFoundException ex) {
//                JOptionPane.showMessageDialog(rootPane,"Không thể mở");          
//            }
//        }
//        lblFileChoose.setText( f.getName());
//    }
    
//    private void writeFile(){
//    
//        // TODO add your handling code here:
//        JFileChooser chooser = new JFileChooser();
//        chooser.showSaveDialog(this);
//        //file select
//        File f = chooser.getSelectedFile();
//        
//        if(f != null){
//            Formatter saveFile;
//            try {
//                String input = txtCipherText.getText();
//                saveFile = new Formatter(f);
//                saveFile.format("%s", input);
//                saveFile.close();
//                 JOptionPane.showMessageDialog(null, "Lưu thành công");
//            } catch (FileNotFoundException ex) {
//                JOptionPane.showMessageDialog(rootPane,"cannot open file");
//
//            }
//        
//    }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRSA().setVisible(true);
            }
        });
    }
    
    // <editor-fold defaultstate="collapsed" desc="File">
    private SecretKey generateKey( ){
        KeyGenerator keygenerator;
        try {
            keygenerator = KeyGenerator.getInstance("DES");//change here
            SecretKey Key  = keygenerator.generateKey();
            
           
            return Key;
        } catch (NoSuchAlgorithmException ex) {
            System.out.println("error");
        }
        return null;
    }
    private String encodeKey ( SecretKey key ){
        String encodedKey = "";
        if(key != null){
            encodedKey = Base64.getEncoder().encodeToString(key.getEncoded());
        }
        return encodedKey;
    }
    
    private SecretKey decodeKey (String encodeKey ){
        
        if(!encodeKey.isEmpty()){
            byte[] decodedKey;
            
            decodedKey = Base64.getDecoder().decode(encodeKey);
            
            SecretKey originalKey = new SecretKeySpec(decodedKey, 0, decodedKey.length, "DES");//change here
            
            return  originalKey;
        }
        return null;
    }
    private byte[] encryptFile(File file, SecretKey key){
        
        Cipher desCipher;
        try {
            byte[] fileContent = Files.readAllBytes(file.toPath());
            
            desCipher = Cipher.getInstance("DES/ECB/PKCS5Padding");//change here
            desCipher.init(Cipher.ENCRYPT_MODE, key);
            byte[] textEncrypted = desCipher.doFinal(fileContent);
            return  textEncrypted;
            
        } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IllegalBlockSizeException | BadPaddingException | IOException ex) {
            System.out.println("err");
        }
        return  null;
    }
    
    private byte[] decryptFile(File file, SecretKey key){
        Cipher desCipher;
        try {
            byte[] fileContent = Files.readAllBytes(file.toPath());
            
            desCipher = Cipher.getInstance("DES/ECB/PKCS5Padding");//change here
            
            desCipher.init(Cipher.DECRYPT_MODE, key);
            
            byte[] textDecrypted = desCipher.doFinal(fileContent);
            
            return  textDecrypted;
            
        } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IllegalBlockSizeException | BadPaddingException | IOException ex) {
            System.out.println("err");
        }
        return  null;
    }
    
    private void demo(){
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();
        
        try {
            
            String extension = f.toString().split("[.]")[1];
            
            
            SecretKey key = generateKey();
            
            byte[] textEncrypt = encryptFile(f, key);
            
            FileUtils.writeByteArrayToFile(new File("E:\\encrypt."+extension), textEncrypt);
            
            byte[] textDecrypt = decryptFile(new File("E:\\encrypt."+extension), key);
            
            FileUtils.writeByteArrayToFile(new File("E:\\decrypt."+extension), textDecrypt);
            
        } catch (IOException ex) {
            System.out.println("err");
        }
    }
    // </editor-fold>  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboCipherStyle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFileChoose;
    private javax.swing.JTextField txtCipherText;
    private javax.swing.JTextField txtPlainText;
    private javax.swing.JTextField txtPlainText1;
    private javax.swing.JTextField txtPlainText2;
    // End of variables declaration//GEN-END:variables
}
